examples/urls.py
from django.urls import path



from django.conf.urls import url, include
from rest_framework import routers
from . import views
router = routers.DefaultRouter()
router.register(r'bookslist', views.BooksListViewSet)

urlpatterns = [
    url('^api/', include(router.urls)),
    path('', views.Index.as_view(), name='index'),
    path('create/', views.BookCreateView.as_view(), name='create_book'),
    path('update/<int:pk>', views.BookUpdateView.as_view(), name='update_book'),
    path('read/<int:pk>', views.BookReadView.as_view(), name='read_book'),
    path('delete/<int:pk>', views.BookDeleteView.as_view(), name='delete_book'),
    path('books/', views.books, name='books'),
    path('multiple_books_edit/', views.multiple_edit, name='multiple_edit'),
    path('multiple_book_delete/', views.multiple_delete, name='multiple_delete'),
]

setup/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('examples.urls')),
]

examples/models.py
from django.db import models
class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50,blank=True)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2,blank=True)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    timestamp = models.DateField(auto_now_add=True, auto_now=False)

bootstrap_modal_forms/forms.py
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


class BSModalForm(PopRequestMixin, forms.Form):
    pass


class BSModalModelForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    pass

examples/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Book


class BookFilterForm(BSModalForm):
    type = forms.ChoiceField(choices=Book.BOOK_TYPES)

    class Meta:
        fields = ['type', 'clear']


class BookModelForm(BSModalModelForm):
    publication_date = forms.DateField(
        error_messages={'invalid': 'Enter a valid date in YYYY-MM-DD format.'}
    )

    class Meta:
        model = Book
        exclude = ['timestamp']


class CustomUserCreationForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class Bookform(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title','author','price']

examples/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic
from rest_framework import viewsets, permissions, filters, mixins, generics, status

from bootstrap_modal_forms.generic import (
    BSModalLoginView,
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalReadView,
    BSModalDeleteView
)

from .forms import (
    BookModelForm,
    Bookform,
    CustomUserCreationForm,
    CustomAuthenticationForm,
    BookFilterForm
)
from .models import Book
from django.shortcuts import render,get_object_or_404,redirect
from rest_framework import viewsets
from .serializers import BookSerializer


class BooksListViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all().order_by('id')
    serializer_class = BookSerializer
    filter_backends = (filters.OrderingFilter, filters.SearchFilter,)
    ordering_fields = ('id', 'title','author')
    search_fields = ordering_fields

class Index(generic.ListView):
    model = Book
    context_object_name = 'books'
    template_name = 'index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if 'type' in self.request.GET:
            qs = qs.filter(book_type=int(self.request.GET['type']))
        return qs


class BookCreateView(BSModalCreateView):
    template_name = 'examples/create_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was created.'
    success_url = reverse_lazy('index')


class BookUpdateView(BSModalUpdateView):
    model = Book
    template_name = 'examples/update_book.html'
    form_class = BookModelForm
    success_message = 'Success: Book was updated.'
    success_url = reverse_lazy('index')


class BookReadView(BSModalReadView):
    model = Book
    template_name = 'examples/read_book.html'


class BookDeleteView(BSModalDeleteView):
    model = Book
    template_name = 'examples/delete_book.html'
    success_message = 'Success: Book was deleted.'
    success_url = reverse_lazy('index')

def books(request):
    data = dict()
    if request.method == 'GET':
        books = Book.objects.all()
        data['table'] = render_to_string(
            '_books_table.html',
            {'books': books},
            request=request
        )
        return JsonResponse(data)


def multiple_edit(request):
    if request.method == 'POST':
        ids = request.POST.get('ids')
        ids = ids.split(",")
        for id in ids:
            obj = get_object_or_404(Book, pk=id)
            if request.POST.get('title'):
                obj.title = request.POST.get('title')
            if request.POST.get('author'):
                obj.author = request.POST.get('author')
            if request.POST.get('price'):
                obj.price = request.POST.get('price')
            obj.save()
        return redirect('index')
    else:
        form = Bookform()

    context = {'form': form}
    return render(request, 'examples/_modal.html', context)

def multiple_delete(request):
    if request.method == 'POST':
        ids = request.POST.getlist('books_ids[]')
        for id in ids:
            obj = get_object_or_404(Book, pk=id)
            obj.delete()
        return JsonResponse(True, safe=False)
    else:
        return redirect('index')

examples/templates/_books_table.html
<table id="books-table" class="table table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
        <th class="text-center" scope="col">#</th>
        <th class="text-center" scope="col">Title</th>
        <th class="text-center" scope="col">Author</th>
        <th class="text-center" scope="col">Price</th>
        <th class="text-center" scope="col">Action</th>
    </tr>
    </thead>
</table>

examples/templates/_footer.html
<footer class="footer" style="border-top: 1px solid #eee;">
  <div class="container">

  </div>
</footer>

examples/templates/_header.html
{% load static %}

<!-- Header -->
<header style="border-bottom: 1px solid #eee;">
  <!-- Messages -->
  <div>
    {% if messages %}
      {% for message in messages %}
        <div style="border-radius:0;" {% if message.tags %} class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <!-- End Messages -->

</header>
<!-- End Header -->

examples/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

examples/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <!-- Font awesome CSS -->
      <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">
      <!-- Custom CSS -->
      <style media="screen">
      .btn{
          margin-right: 5px;
      }
        .invalid {
          color: #dc3545;
          font-size: 80%;
        }
        body {
          display: flex;
          flex-direction: column;
          min-height: 100vh;
        }
        tr.selected {
            background-color: #80808063 !important;
        }
        .footer {
          margin: auto 0 0;
          height: 56px;
        }
      </style>
    {% endblock stylesheets %}

    <title>Datatable List</title>
  </head>

  <body>

    <!-- Includes -->
    {% include "_header.html" %}

    {% block content %}{% endblock content %}

    <!-- Includes -->
    {% include "_footer.html" %}

    <!-- JavaScript -->
    {% block scripts %}
      <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- You can alternatively load the minified version -->
      <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
      <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
      <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    {% endblock scripts %}
    {% block extrascripts %}{% endblock extrascripts %}
  </body>
</html>

examples/templates/examples/_modal.html
{% load crispy_forms_tags %}
<div class="modal fade" id="contactModal" role="dialog">
        <form method="POST" id="contact-form" enctype="multipart/form-data" action="{% url 'multiple_edit' %}">
            {% csrf_token %}
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Update Multiple Rows</h4>
                        <button type="button" class="close " data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        {{ form|crispy   }}
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="submit" id="contactSubmit" class="btn btn-success">Send</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

examples/templates/examples/create_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Create Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Create</button>
  </div>

</form>

examples/templates/examples/delete_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Delete Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Are you sure you want to delete book with title
      <strong>{{ book.title }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
  </div>

</form>

examples/templates/examples/read_book.html
{% load widget_tweaks %}

<div class="modal-header">
  <h3 class="modal-title">Book details</h3>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">

  <div class="">
    Title:
    {{ book.title }}
  </div>
  <div class="">
    Author:
    {{ book.author }}
  </div>
  <div class="">
    Price:
    {{ book.price }}
    €
  </div>
  <div class="">
    Pages:
    {{ book.pages }}
  </div>
  <div class="">
    Type:
    {{ book.get_book_type_display }}
  </div>
  <div class="">
    Publication date:
    {{ book.publication_date }}
  </div>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

examples/templates/examples/update_book.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Update Book</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Update</button>
  </div>

</form>

examples/templates/index.html
{% extends 'base.html' %}
{% block content %}
  {% include "_modal.html" %}
  <div class="container mt-3">
    <div class="row">
      <div class="col">
        <h4>
          <strong>Custom Datatable </strong>
        </h4>
        <div class="row">
          <div class="col-12 mb-3">
            <button id="create-book" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>New
            </button>
            <button id="edit-book" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-pencil mr-2"></span>Edit
            </button>
            <button id="delete-book" class="btn btn-primary" type="button" name="button">
              <span class="fa fa-trash mr-2"></span>Delete
            </button>
          </div>
          <div class="col-12 mb-3">
              {% include "_books_table.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
<div id="mmodal"></div>
{% endblock content %}
{% block extrascripts %}
  <script type="text/javascript">
      $(function () {
            var table = $('#books-table').DataTable({
                "responsive": true,
                select: true,
                "ajax":{
                    url:"/api/bookslist/?format=datatables",
                },
                "columns": [
                    {"data": "id"},
                    {"data": "title"},
                    {"data": "author"},
                    {"data": "price"},
                    {
                        data: "action",
                        render: function ( data, type, row, meta ) {
                            var read_book_url = "{% url 'read_book' 123 %}";
                                read_book_url =  read_book_url.replace(123, row.id);
                            var update_book_url = "{% url 'update_book' 123 %}";
                                update_book_url =  update_book_url.replace(123, row.id);
                            var delete_book_url = "{% url 'delete_book' 123 %}";
                                delete_book_url =  delete_book_url.replace(123, row.id);
                            return   '<button type="button" class="bs-modal read-book btn btn-sm btn-primary" data-form-url="'+read_book_url+'">'+
                                      '<span class="fa fa-eye"></span></button>'+
                                      '<button type="button" class="update-book btn btn-sm btn-primary" data-form-url="'+update_book_url+'">'+
                                      '<span class="fa fa-pencil"></span></button>'+
                                      '<button type="button" class="bs-modal delete-book btn btn-sm btn-danger" data-form-url="'+delete_book_url+'">'+
                                      '<span class="fa fa-trash"></span></button>';
                        }
                    },
                ],


            });
          $('#books-table tbody').on( 'click', 'tr', function () {
                $(this).toggleClass('selected');
            });
            $('#edit-book').click( function () {
                if(table.rows('.selected').data().length > 0){
                    var modalDiv = $("#mmodal");
                    $.ajax({
                      url: "{% url 'multiple_edit' %}",
                      success: function(data) {
                          $('#mmodal').html(data);
                          $("#contactModal").modal('show');
                          var ids = [];
                          $(".selected").each(function () {
                              var id = $(this).find('td:first').text();
                              ids.push(id);
                          });
                           $("#contactModal").find('form').append('<input type="hidden" name="ids" value="'+ids+'">');
                      }
                    });
                }else{
                     toastr.error('Select at least one row')
                }
            });
            $('#delete-book').click( function () {
                if(table.rows('.selected').data().length > 0){
                    var books_ids = [];
                    $(".selected").each(function () {
                        var id = $(this).find('td:first').text();
                        books_ids.push(id);
                    });
                    $.ajax({
                       method : "post",
                       dataType : "json",
                       data:{'books_ids':books_ids, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                       url: "{% url 'multiple_delete' %}",
                       success: function(data) {
                           toastr.success('Selected record deleted successfully')
                           location.reload();
                      }
                    });
                }else{
                     toastr.error('Select at least one row')
                }
            });
          // Create book button opens modal with id="create-modal"
          $("#create-book").modalForm({
            formURL: "{% url 'create_book' %}",
            modalID: "#create-modal"
          });
          var asyncSuccessMessage = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");
          setTimeout(function(){
              $(".update-book").each(function () {
                  $(this).modalForm(
                       {formURL: $(this).data("form-url")}
                  );
              });
              // Delete book buttons
              $(".bs-modal").each(function () {
                  $(this).modalForm({formURL: $(this).data("form-url")});
              });
          }, 1000);
          // Hide message
          $(".alert").fadeTo(2000, 500).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
  </script>
{% endblock extrascripts %}